export const metodosParaDesativar = {
  standard: [
    'replaceOrCreate',
    'patchOrCreate',
    'exists',
    'find',
    'findOne',
    'count',
    'replaceById',
    'createChangeStream',
    'updateAll',
    'replaceOrCreate',
    'replaceById',
    'upsertWithWhere',
  ],
  usuario: ['prototype.__get__usuario'],
  tags: [
    'prototype.__get__tags',
    'prototype.__create__tags',
    'prototype.__count__tags',
    'prototype.__delete__tags',
    'prototype.__destroyById__tags',
    'prototype.__link__tags',
    'prototype.__unlink__tags',
    'prototype.__findById__tags',
    'prototype.__updateById__tags',
    'prototype.__exists__tags',
  ],
}
