export const metodosParaDesativar = {
  standard: [
    'replaceOrCreate',
    'patchOrCreate',
    'exists',
    'find',
    'findOne',
    'count',
    'replaceById',
    'createChangeStream',
    'updateAll',
    'replaceOrCreate',
    'replaceById',
    'upsertWithWhere',
  ],
  usuario: ['prototype.__get__usuario'],
  provas: [
    'prototype.__get__provas',
    'prototype.__create__provas',
    'prototype.__count__provas',
    'prototype.__delete__provas',
    'prototype.__destroyById__provas',
    'prototype.__link__provas',
    'prototype.__unlink__provas',
    'prototype.__findById__provas',
    'prototype.__updateById__provas',
    'prototype.__exists__provas',
  ],
}
