image: node:8.11

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build-test
  - quality-analysis
  - package
  - deploy

test:
  stage: build-test
  script:
    - npm install
    - npm run lint
    - npm test error coverage
  artifacts:
    paths:
      - ./
    expire_in: 1 day

sonar:
  stage: quality-analysis
  allow_failure: true
  script:
    - npm install -g sonarqube-scanner
    - sonar-scanner -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.projectName=$CI_PROJECT_NAME -Dsonar.projectVersion=1.0-SNAPSHOT -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN

package-dev:
  image: docker:latest
  services:
    - docker:dind
  stage: package
  script:
    - docker version
    - docker system prune -a -f
    - apk update && apk upgrade && apk add --no-cache bash git openssh
    # - apk add --update nodejs
    # - npm install
    - docker build -t $DOCKER_REGISTRY:dev .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push $DOCKER_REGISTRY:dev
  only:
    - develop

package-tag:
  image: docker:latest
  services:
    - docker:dind
  stage: package
  script:
    - docker version
    - docker system prune -a -f
    - apk update && apk upgrade && apk add --no-cache bash git openssh
    - docker build -t $DOCKER_REGISTRY:$CI_COMMIT_REF_NAME .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push $DOCKER_REGISTRY:$CI_COMMIT_REF_NAME
  only:
    - tags

package-master:
  image: docker:latest
  services:
    - docker:dind
  stage: package
  script:
    - docker version
    - docker system prune -a -f
    - apk update && apk upgrade && apk add --no-cache bash git openssh
    - docker build -t $DOCKER_REGISTRY .
    # - docker build -t $DOCKER_REGISTRY:$CI_COMMIT_SHA .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    # - docker push $DOCKER_REGISTRY:$CI_COMMIT_SHA
    - docker push $DOCKER_REGISTRY:latest
  only:
    - master

deploy-dev-picco:
  image: ubuntu:latest
  services:
    - docker:dind
  stage: deploy
  only:
    - develop
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PICCO_KEY"
    - echo "$SSH_PICCO_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p2046 -H 177.20.148.39  >> ~/.ssh/known_hosts
    - ssh-keyscan -p2046 -H picco.comperve.ufrn.br  >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -p2046 gitlab@picco.comperve.ufrn.br rm -rf multiprova-deploy-dev/ 2>/dev/null || true
    - ssh -p2046 gitlab@picco.comperve.ufrn.br git config --global user.email "gustavo.leitao@imd.ufrn.br"
    - ssh -p2046 gitlab@picco.comperve.ufrn.br git config --global user.name "gustavoleitao"
    - ssh -p2046 gitlab@picco.comperve.ufrn.br git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/tapioca/multiprova/multiprova-deploy.git multiprova-deploy-dev
    - ssh -p2046 gitlab@picco.comperve.ufrn.br docker system prune --force
    - ssh -p2046 gitlab@picco.comperve.ufrn.br docker network create container-picco-network || true
    - ssh -p2046 gitlab@picco.comperve.ufrn.br docker login registry.gitlab.com -u gitlab+deploy-token-3137 -p oWAsikG9ycxWsP2YPtQE
    - ssh -p2046 gitlab@picco.comperve.ufrn.br ./multiprova-deploy-dev/picco/dev/update.sh
  environment:
    name: develop
    url: http://dev.picco.comperve.ufrn.br

deploy-master-picco:
  image: ubuntu:latest
  services:
    - docker:dind
  stage: deploy
  only:
    - master
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PICCO_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p2046 -H 177.20.148.39  >> ~/.ssh/known_hosts
    - ssh-keyscan -p2046 -H picco.comperve.ufrn.br  >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -p2046 gitlab@picco.comperve.ufrn.br rm -rf multiprova-deploy/ 2>/dev/null || true
    - ssh -p2046 gitlab@picco.comperve.ufrn.br git config --global user.email "gustavo.leitao@imd.ufrn.br"
    - ssh -p2046 gitlab@picco.comperve.ufrn.br git config --global user.name "gustavoleitao"
    - ssh -p2046 gitlab@picco.comperve.ufrn.br git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/tapioca/multiprova/multiprova-deploy.git
    - ssh -p2046 gitlab@picco.comperve.ufrn.br docker system prune --force
    - ssh -p2046 gitlab@picco.comperve.ufrn.br docker network create container-picco-network || true
    - ssh -p2046 gitlab@picco.comperve.ufrn.br docker login registry.gitlab.com -u gitlab+deploy-token-3137 -p oWAsikG9ycxWsP2YPtQE
    - ssh -p2046 gitlab@picco.comperve.ufrn.br ./multiprova-deploy/picco/master/update.sh
  environment:
    name: production
    url: http://picco.comperve.ufrn.br

deploy-dev-educaio:
  image: ubuntu:latest
  services:
    - docker:dind
  stage: deploy
  only:
    - develop
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_EDUCAIO_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p2046 -H 177.20.148.40  >> ~/.ssh/known_hosts
    - ssh-keyscan -p2046 -H educaio.ufrn.br  >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -p2046 gitlab@educaio.ufrn.br rm -rf multiprova-deploy-dev/ 2>/dev/null || true
    - ssh -p2046 gitlab@educaio.ufrn.br git config --global user.email "gustavo.leitao@imd.ufrn.br"
    - ssh -p2046 gitlab@educaio.ufrn.br git config --global user.name "gustavoleitao"
    - ssh -p2046 gitlab@educaio.ufrn.br git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/tapioca/multiprova/multiprova-deploy.git multiprova-deploy-dev
    - ssh -p2046 gitlab@educaio.ufrn.br docker system prune --force
    - ssh -p2046 gitlab@educaio.ufrn.br docker network create container-educaio-network || true
    - ssh -p2046 gitlab@educaio.ufrn.br docker login registry.gitlab.com -u gitlab+deploy-token-3137 -p oWAsikG9ycxWsP2YPtQE
    - ssh -p2046 gitlab@educaio.ufrn.br ./multiprova-deploy-dev/educaio/dev/update.sh
  environment:
    name: develop
    url: http://dev.educaio.ufrn.br

deploy-master-educaio:
  image: ubuntu:latest
  services:
    - docker:dind
  stage: deploy
  only:
    - master
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_EDUCAIO_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p2046 -H 177.20.148.40  >> ~/.ssh/known_hosts
    - ssh-keyscan -p2046 -H educaio.ufrn.br  >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -p2046 gitlab@educaio.ufrn.br rm -rf multiprova-deploy/ 2>/dev/null || true
    - ssh -p2046 gitlab@educaio.ufrn.br git config --global user.email "gustavo.leitao@imd.ufrn.br"
    - ssh -p2046 gitlab@educaio.ufrn.br git config --global user.name "gustavoleitao"
    - ssh -p2046 gitlab@educaio.ufrn.br git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/tapioca/multiprova/multiprova-deploy.git
    - ssh -p2046 gitlab@educaio.ufrn.br docker system prune --force
    - ssh -p2046 gitlab@educaio.ufrn.br docker network create container-educaio-network || true
    - ssh -p2046 gitlab@educaio.ufrn.br docker login registry.gitlab.com -u gitlab+deploy-token-3137 -p oWAsikG9ycxWsP2YPtQE
    - ssh -p2046 gitlab@educaio.ufrn.br ./multiprova-deploy/educaio/master/update.sh
  environment:
    name: production
    url: http://educaio.ufrn.br

