export { validarSenhaAntesDeSerCriptografada } from './validarSenhaAntesDeSerCriptografada'
export { mapearPropriedadePermissoesParaRoles } from './mapearPropriedadePermissoesParaRoles'
export { mapearRolesParaPropriedadePermissoes } from './mapearRolesParaPropriedadePermissoes'
export { emailExiste } from './emailExiste'
export { forgotPassword, updateForgottenPassword, sendValidatePassword, updatePassword } from './password'
export { usernameExiste } from './usernameExiste'
export { metodosParaDesativar } from './metodosParaDesativar'
export { metodosCriacao } from './metodosCriacao'
export { datetimeServidor } from './datetimeServidor'
export { aplicarRoleAoUsuario } from './mapearPropriedadePermissoesParaRoles/aplicarRoleAoUsuario'
export { getUsuariosDocente } from './getUsuariosDocente'
export { getUsuariosDiscentes, getUsuariosDiscentesByEmail } from './getUsuariosDiscentes'
export { enumTipoUsuario } from './enumTipoUsuario'
export { atualizaStatusProvas } from './atualizaStatusProvas'
export { getTurmasDoDocente } from './getTurmasDoDocente'
export { estatisticasAcademicas } from './estatisticasAcademicas'
export { estatisticasProvasAplicadas } from './estatisticasProvasAplicadas'
export { getEstatisticasQuestoes, getEstatisticasQuestoesByIdDocente } from './estatisticasQuestoes'
export { criarAluno } from './criarAluno'
export { getEstatisticasInstanciaByIdDocente } from './estatisticasInstanciasDocente'
export { getEstatisticasProvaByIdDocente } from './estatisticasProvasDocente'
export { getEstatisticasInstanciaByIdDiscente } from './estatisticasProvasDiscente'
export { getAcumuladoDasInstancias } from './acumuladoDasInstancias'
export { getAlunosEmLote } from './getAlunosEmLote'
export { criarUsuarioAluno } from './criarAluno'
export { getUsuariosByPerfil, countUsuariosByPerfil } from './usuariosByPerfil'
