export const metodosParaDesativar = {
  standard: [
    'replaceOrCreate',
    'patchOrCreate',
    'exists',
    'findOne',
    'createChangeStream',
    'updateAll',
    'upsertWithWhere',
    'changePassword',
    'resetPassword',
    'reset',
  ],
  accessTokens: [
    'prototype.__count__accessTokens',
    'prototype.__create__accessTokens',
    'prototype.__delete__accessTokens',
    'prototype.__destroyById__accessTokens',
    'prototype.__findById__accessTokens',
    'prototype.__get__accessTokens',
    'prototype.__updateById__accessTokens',
    'prototype.__resetPassword__accessTokens',
  ],
  questoes: [
    'prototype.__create__questoes',
    'prototype.__findById__questoes',
    'prototype.__updateById__questoes',
    'prototype.__destroyById__questoes',
    'prototype.__delete__questoes',
  ],
  provas: [
    'prototype.__create__provas',
    'prototype.__findById__provas',
    'prototype.__updateById__provas',
    'prototype.__destroyById__provas',
    'prototype.__delete__provas',
  ],
  cadernos: [
    'prototype.__create__cadernos',
    'prototype.__findById__cadernos',
    'prototype.__updateById__cadernos',
    'prototype.__destroyById__cadernos',
    'prototype.__delete__cadernos',
  ],
  concursos: [
    'prototype.__create__concursos',
    'prototype.__findById__concursos',
    'prototype.__updateById__concursos',
    'prototype.__destroyById__concursos',
    'prototype.__delete__concursos',
  ],
  impressoes: [
    'prototype.__get__impressoes',
    'prototype.__create__impressoes',
    'prototype.__findById__impressoes',
    'prototype.__updateById__impressoes',
    'prototype.__destroyById__impressoes',
    'prototype.__count__impressoes',
    'prototype.__delete__impressoes',
  ],
  instanciamentos: [
    'prototype.__get__instanciamentos',
    'prototype.__create__instanciamentos',
    'prototype.__findById__instanciamentos',
    'prototype.__updateById__instanciamentos',
    'prototype.__destroyById__instanciamentos',
    'prototype.__count__instanciamentos',
    'prototype.__delete__instanciamentos',
  ],
  instanciamentosConcursos: [
    'prototype.__create__instanciamentosConcursos',
    'prototype.__updateById__instanciamentosConcursos',
    'prototype.__destroyById__instanciamentosConcursos',
    'prototype.__count__instanciamentosConcursos',
    'prototype.__delete__instanciamentosConcursos',
  ],
  tags: [
    'prototype.__create__tags',
    'prototype.__findById__tags',
    'prototype.__updateById__tags',
    'prototype.__destroyById__tags',
    'prototype.__delete__tags',
  ],
  questoesCriadas: [
    'prototype.__get__questoesCriadas',
    'prototype.__create__questoesCriadas',
    'prototype.__findById__questoesCriadas',
    'prototype.__updateById__questoesCriadas',
    'prototype.__destroyById__questoesCriadas',
    'prototype.__count__questoesCriadas',
    'prototype.__delete__questoesCriadas',
  ],
  provasCriadas: [
    'prototype.__get__provasCriadas',
    'prototype.__create__provasCriadas',
    'prototype.__findById__provasCriadas',
    'prototype.__updateById__provasCriadas',
    'prototype.__destroyById__provasCriadas',
    'prototype.__count__provasCriadas',
    'prototype.__delete__provasCriadas',
  ],
  usuariosCriados: [
    'prototype.__get__usuariosCriados',
    'prototype.__create__usuariosCriados',
    'prototype.__findById__usuariosCriados',
    'prototype.__updateById__usuariosCriados',
    'prototype.__destroyById__usuariosCriados',
    'prototype.__count__usuariosCriados',
    'prototype.__delete__usuariosCriados',
  ],
  turmas: [
    'prototype.__create__turmas',
    'prototype.__findById__turmas',
    'prototype.__updateById__turmas',
    'prototype.__destroyById__turmas',
    'prototype.__delete__turmas',
  ],
  notificacoes: [
    'prototype.__create__notificacoes',
    'prototype.__destroyById__notificacoes',
    'prototype.__count__notificacoes',
  ],
}
