export const metodosDesativadosConcurso = [
  //concurso
  'replaceOrCreate',
  'patchOrCreate',
  'exists',
  'find',
  'findOne',
  'count',
  'replaceById',
  'createChangeStream',
  'updateAll',
  'replaceOrCreate',
  'replaceById',
  'upsertWithWhere',
  //usuario
  'prototype.__get__usuario',
  //cargos
  'prototype.__findById__cargosList',
  'prototype.__count__cargosList',
  'prototype.__delete__cargosList',
  'prototype.__updateById__cargosList',
  'prototype.__destroyById__cargosList',
  //cadernos
  'prototype.__delete__cadernosList',
  'prototype.__updateById__cadernosList',
  'prototype.__destroyById__cadernosList',
  'prototype.__create__cadernosList',
  //provas
  'prototype.__delete__provasList',
  //questoes
  'prototype.__delete__questoesList',
]
