exports.testData = {
  ids: {
    docente: null,
    professor: null,
    discente: null,
    admin: null,
    gestor: null,
    questaoDoDocente: null,
    questaoDoDocenteVouF: null,
    questaoDoDocenteDiscursiva: null,
    questaoDoDocenteAssociacaoDeColunas: null,
    questaoDoDocenteQuestaoBloco: null,
    questaoDoDocenteRedacao: null,
    concursoDoDocente: null,
    concursoDoDocenteEtapa: null,
    concursoDoDocenteCargo: null,
    provaProntaParaAplicacao: '5f60dce5-7ee1-436b-9b5d-0746b4aea25f',
    instanciaParaSalvarResposta: '568c28fffc4be30d44d0000x',
    provaVistaProva: '8f48f5d8-a320-4e99-8817-5e934bd63525',
    instanciaInvalida: '568c28fffc4be30d44d0000z',
    usuario: '',
  },
  tokens: {
    docente: null,
    professor: null,
    discente: null,
    admin: null,
    gestor: null,
  },
}
